import { test, expect } from '@playwright/test'
import { defaults } from '../src/draftModel'

test('draft contains ceremony details and a deferred venue map', async ({ page }) => {
  await page.setViewportSize({ width:390, height:844 })
  await page.goto('draft/')
  await expect(page.locator('.draft-date-card time')).toHaveAttribute('datetime', '2026-11-07T19:20:00+09:00')
  await expect(page.locator('.draft-date-card')).toContainText('오후 7시 20분')
  await expect(page.locator('.draft-location-card')).toContainText('3층 베일리홀')
  await expect(page.locator('.draft-location-card address')).toHaveText('서울특별시 구로구 경인로 610')
  await expect(page.locator('.draft-location-map .leaflet-tile')).toHaveCount(0)
  await page.locator('.draft-location').scrollIntoViewIfNeeded()
  await expect(page.getByRole('region', {name:'더링크호텔 위치 지도'})).toBeVisible()
  await expect(page.getByTitle('더링크호텔 · 3층 베일리홀')).toBeVisible()
  await expect(page.getByRole('link', {name:'네이버지도 ↗'})).toHaveAttribute('href', /map\.naver\.com/)
  await expect(page.getByRole('link', {name:'카카오맵 ↗'})).toHaveAttribute('href', /map\.kakao\.com/)
})

test('legacy yellow migration, rotation handle, persistence and playback', async ({ page }) => {
  await page.setViewportSize({ width:1440, height:1000 })
  await page.goto('draft/')
  const legacy = JSON.parse(JSON.stringify(defaults))
  delete legacy.intro.rotation; delete legacy.main.rotation
  legacy.intro.color = '#FFF5DE'; legacy.intro.text = 'Our\nWedding'; legacy.intro.y = 26
  await page.evaluate(value => localStorage.setItem('wedding-draft-v1', JSON.stringify(value)), legacy)
  await page.reload()
  await expect(page.getByLabel('레터링 색상')).toHaveValue('#f4d84f')
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('Our\nWedding')
  await expect(page.getByLabel('세로 위치', {exact:true})).toHaveValue('26')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  const selection = page.locator('.draft-selection')
  const rotator = page.getByRole('slider', {name:'문구 회전 핸들'})
  await rotator.scrollIntoViewIfNeeded()
  const handle = (await rotator.boundingBox())!, block = (await selection.boundingBox())!
  const cx = block.x + block.width/2, cy = block.y + block.height/2
  const radius = cy - (handle.y + handle.height/2)
  await page.mouse.move(handle.x + handle.width/2, handle.y + handle.height/2)
  await page.mouse.down(); await page.mouse.move(cx + radius*.5, cy - radius*Math.sqrt(3)/2, {steps:8}); await page.mouse.up()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('30')
  await page.getByRole('button', {name:'되돌리기', exact:true}).click()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  await page.getByLabel('회전 각도', {exact:true}).fill('-18')
  await expect(selection).toHaveAttribute('style', /rotate\(-18deg\)/)
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('wedding-draft-v1')!).intro.rotation)).toBe(-18)
  await page.reload()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('-18')
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name:'설정 내보내기'}).click()
  const exported = await download
  await page.getByRole('button', {name:'수평으로', exact:true}).click()
  await page.locator('input[type=file]').setInputFiles((await exported.path())!)
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('-18')
  await page.getByRole('button', {name:'메인 커버', exact:true}).click()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  await page.getByLabel('회전 각도', {exact:true}).fill('12')
  await page.getByRole('button', {name:'전체 재생'}).click()
  await expect(page.locator('.draft-intro-layer .draft-letter-position')).toHaveAttribute('style', /rotate\(-18deg\)/)
  await page.getByRole('button', {name:'건너뛰기'}).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  await expect(page.locator('.draft-cover-layer .draft-letter-position')).toHaveAttribute('style', /rotate\(12deg\)/)
})

test('edit, drag, resize, save, export/import and independent scene settings', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  const config = () => page.evaluate(() => JSON.parse(localStorage.getItem('wedding-draft-v1')!))
  const selection = page.getByRole('group', { name: '문구 이동 및 크기 조절' })
  const initialBox = (await selection.boundingBox())!
  await page.mouse.move(initialBox.x + 40, initialBox.y + 40)
  await page.mouse.down(); await page.mouse.move(initialBox.x + 40, initialBox.y + 90, { steps: 8 }); await page.mouse.up()
  await expect.poll(async () => (await config()).intro.y).toBeGreaterThan(25)
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.poll(async () => (await config()).intro.y).toBe(22)
  await selection.dblclick()
  await page.getByLabel('사진 위에서 문구 편집').fill('Together\nforever')
  await page.getByLabel('사진 위에서 문구 편집').press('Escape')
  await expect(selection.locator('svg')).toHaveAttribute('aria-label', 'Together\nforever')
  await selection.focus(); await page.keyboard.press('ArrowDown')
  await expect.poll(async () => (await config()).intro.y).toBe(23)
  const handle = page.getByRole('slider', { name: '문구 크기 핸들' })
  await handle.focus(); await handle.press('ArrowLeft')
  await expect.poll(async () => (await config()).intro.width).toBe(85)
  const corner = (await handle.boundingBox())!
  await page.mouse.move(corner.x + 8, corner.y + 8); await page.mouse.down()
  await page.mouse.move(corner.x - 12, corner.y + 8, { steps: 5 }); await page.mouse.up()
  await expect.poll(async () => (await config()).intro.width).toBeLessThan(85)
  await page.getByRole('button', { name: '메인 커버', exact: true }).click()
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Wedding\nInvitation')
  await page.getByLabel('사진 위 문구', { exact: true }).fill('Our\nWedding')
  await page.getByRole('button', { name: '미스트 블루 배경' }).click()
  await expect(page.locator('.draft-poster-body')).toHaveCSS('background-color', 'rgb(234, 240, 245)')
  await expect.poll(async () => (await config()).main.text).toBe('Our\nWedding')
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Together\nforever')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '설정 내보내기' }).click()
  const exportFile = await download
  expect(exportFile.suggestedFilename()).toBe('wedding-draft.json')
  await page.getByRole('button', { name: '이 장면 초기화' }).click()
  await page.locator('input[type=file]').setInputFiles((await exportFile.path())!)
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Together\nforever')
  await page.getByLabel('사진 위 문구', { exact: true }).fill('한글')
  await expect(page.locator('.draft-notice')).toContainText('기본 글꼴')
  await expect(selection.locator('svg')).toHaveAttribute('aria-label', '한글')
  await page.locator('input[type=file]').setInputFiles({ name:'invalid.json', mimeType:'application/json', buffer:Buffer.from('{"version":100}') })
  await expect(page.locator('.draft-notice')).toContainText('파일 형식')
})

test('empty text and immediate reload retain position and rotation', async ({ page }) => {
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', {name:'문구 편집', exact:false}).click()
  const input = page.getByLabel('사진 위에서 문구 편집')
  await input.press('ControlOrMeta+A')
  await input.press('Backspace')
  await page.getByRole('button', {name:'편집 완료'}).click()
  await page.getByLabel('세로 위치', {exact:true}).fill('35')
  await page.getByLabel('회전 각도', {exact:true}).fill('12')
  // Intentionally no polling or delay before reload: edits must already be durable.
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('')
  await expect(page.getByLabel('세로 위치', {exact:true})).toHaveValue('35')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('12')
  await page.getByRole('button', {name:'문구 편집', exact:false}).click()
  await page.getByLabel('사진 위에서 문구 편집').pressSequentially('Our wedding')
  await page.getByRole('button', {name:'편집 완료'}).click()
  await page.getByRole('button', {name:'지금 저장', exact:true}).click()
  await expect(page.locator('.draft-notice')).toContainText('새로고침해도 유지')
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('Our wedding')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('12')
})

test('intro transitions, replay, gallery and mobile editing', async ({ page }) => {
  await page.setViewportSize({ width:390, height:844 })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', { name:'문구 · 배경 편집' }).click()
  await expect(page.getByLabel('사진 위 문구', { exact:true })).toBeVisible()
  await page.getByRole('button', { name:'메인 커버', exact:true }).click()
  await page.getByRole('button', { name:'편집 도구 닫기' }).click()
  await expect(page.locator('.draft-letter-svg')).toHaveAttribute('aria-label', 'Wedding\nInvitation')
  await page.screenshot({ path:'/private/tmp/wedding-draft-mobile-edit.png' })
  await page.getByRole('button', { name:'전체 재생' }).click()
  await expect(page.locator('.draft-intro-layer')).toBeVisible()
  await expect(page.locator('.draft-cover-layer svg')).toHaveCount(0)
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0, {timeout:10000})
  await expect(page.locator('.draft-cover-layer svg')).toBeVisible()
  await expect(page.locator('.draft-cover-layer .draft-write').last()).toHaveCSS('clip-path', 'none', { timeout:5000 })
  await page.screenshot({ path:'/private/tmp/wedding-draft-mobile-cover.png' })
  await page.locator('.draft-greeting').scrollIntoViewIfNeeded()
  await expect(page.locator('.draft-greeting h2')).toHaveCSS('opacity', '1')
  await page.screenshot({ path:'/private/tmp/wedding-draft-body.png' })
  await page.getByRole('button', { name:'다시 재생' }).click()
  await expect(page.locator('.draft-intro-layer')).toBeVisible()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0, {timeout:10000})
  await page.getByRole('button', { name:'메인 커버 사진 크게 보기' }).click()
  await expect(page.locator('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('short screens, viewport bounds and reduced motion', async ({ page }) => {
  await page.setViewportSize({width:320,height:568})
  await page.emulateMedia({ reducedMotion:'reduce' })
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', { name:'문구 · 배경 편집' }).click()
  await page.getByLabel('가로 위치', {exact:true}).fill('0')
  await page.getByLabel('세로 위치', {exact:true}).fill('0')
  await page.getByRole('button', { name:'편집 도구 닫기' }).click()
  const block = (await page.locator('.draft-selection').boundingBox())!
  const stage = (await page.locator('.draft-stage').boundingBox())!
  expect(block.x).toBeGreaterThanOrEqual(stage.x - 1)
  expect(block.y).toBeGreaterThanOrEqual(stage.y - 1)
  await page.getByRole('button', { name:'전체 재생' }).click()
  await expect(page.locator('.draft-write').first()).toHaveCSS('animation-name','none')
  await page.getByRole('button', { name:'건너뛰기' }).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  await page.getByRole('button', { name:'편집으로' }).click()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})
