import { test, expect } from '@playwright/test'
import { defaults } from '../src/draftModel'
import { parseConfig } from '../src/draftModel'
import { parseCeremonyDate, ceremonyLabel, ceremonyCountdown } from '../src/draftDate'
import { createWeddingCalendar } from '../src/draftCalendarFile'

test('published defaults preserve the approved Zen lettering layout', () => {
  expect(defaults.intro).toEqual({text:"We're getting\nmarried",x:51,y:24.209302325581397,width:94,color:'#F4D84F',rotation:-8})
  expect(defaults.main).toEqual({text:'Wedding\nInvitation',x:50,y:16.88372093023256,width:76.32558139534883,color:'#203F76',rotation:0})
})

test('published preview ignores local edits without deleting them', async ({ page }) => {
  const custom = structuredClone(defaults)
  custom.intro.rotation = 22
  custom.copy.greetingTitle = '이 기기의 편집값'
  await page.addInitScript(value => localStorage.setItem('wedding-draft-v1',JSON.stringify(value)),custom)
  await page.goto('draft/?mode=preview&source=published')
  await expect(page.locator('.draft-greeting h2')).toContainText(defaults.copy.greetingTitle)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('wedding-draft-v1')!).intro.rotation)).toBe(22)
  await page.getByRole('button',{name:'← 편집으로'}).click()
  await expect(page.getByLabel('회전 각도',{exact:true})).toHaveValue('22')
  await expect(page.locator('.draft-greeting h2')).toContainText('이 기기의 편집값')
})

test('calendar file uses edited details and the Korean ceremony instant', () => {
  const ics = createWeddingCalendar(defaults.copy, new Date('2026-09-25T00:00:00Z'))!
  const unfolded = ics.replace(/\r\n /g, '')
  expect(unfolded).toContain('DTSTART:20261107T102000Z')
  expect(unfolded).toContain('SUMMARY:정주현 ♥ 임하니 결혼식')
  expect(unfolded).toContain('3층 베일리홀')
  expect(unfolded).not.toContain('DTEND:')
  expect(ics.endsWith('END:VCALENDAR\r\n')).toBe(true)
  for (const line of ics.split('\r\n')) expect(new TextEncoder().encode(line).length).toBeLessThanOrEqual(75)
  const edited = createWeddingCalendar({ ...defaults.copy, ceremonyDate:'2026-12-12', ceremonyTime:'09:30', venueName:'홀, A;B\n2층' })!.replace(/\r\n /g, '')
  expect(edited).toContain('DTSTART:20261212T003000Z')
  expect(edited).toContain('LOCATION:홀\\, A\\;B\\n2층')
})

test('countdown uses Korean calendar days including midnight and past dates', () => {
  expect(ceremonyCountdown('2026-11-07', new Date('2026-09-25T00:00:00+09:00'))).toEqual({ days:43, label:'D-43' })
  expect(ceremonyCountdown('2026-11-07', new Date('2026-11-06T14:59:59Z'))?.label).toBe('D-1')
  expect(ceremonyCountdown('2026-11-07', new Date('2026-11-06T15:00:00Z'))?.label).toBe('D-Day')
  expect(ceremonyCountdown('2026-11-07', new Date('2026-11-07T15:00:00Z'))?.label).toBe('D+1')
  expect(ceremonyCountdown('invalid')).toBeNull()
})

test('schedule float stays compact and yields to the calendar', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('draft/?mode=preview')
  const summary = page.locator('.draft-event-float')
  await expect(summary).toContainText('11.07')
  await expect(summary).toContainText('19:20')
  await expect(summary).toContainText('더링크서울')
  await expect(summary).toHaveCSS('width','76px')
  await expect(summary).toHaveCSS('pointer-events','none')
  await expect(summary).toBeVisible()
  await expect(page.locator('.draft-countdown strong')).toHaveText(/^D(?:-Day|[-+]\d+)$/)
  await expect(page.locator('.draft-date-heading .draft-countdown')).toHaveCount(1)
  await expect(page.locator('.draft-date-card .draft-countdown')).toHaveCount(0)
  await expect(page.locator('.draft-event-float')).toHaveCSS('background-color','rgba(24, 49, 61, 0.2)')
  await expect(page.locator('.draft-bgm-glass')).toHaveCSS('background-color','rgba(24, 49, 61, 0.2)')
  await expect(page.locator('.draft-rsvp')).toHaveCount(0)
  const calendarLink = page.getByRole('link', {name:'결혼식 일정 캘린더에 추가',exact:true})
  await expect(calendarLink).toHaveAttribute('href','/mobile-wedding-invitation/calendar/wedding.ics')
  await expect(calendarLink).not.toHaveAttribute('download')
  const heading = (await page.locator('.draft-date-heading h2').boundingBox())!
  const badge = (await page.locator('.draft-countdown').boundingBox())!
  expect(badge.x).toBeGreaterThanOrEqual(heading.x + heading.width)
  await page.locator('.draft-calendar').scrollIntoViewIfNeeded()
  await expect(summary).toHaveAttribute('aria-hidden','true')
  await expect(summary).toHaveCSS('opacity','0')
  await page.locator('.draft-accounts-section').scrollIntoViewIfNeeded()
  await expect(summary).toBeVisible()
  await expect(summary).not.toHaveAttribute('aria-hidden','true')
  await page.locator('.draft-stage').scrollIntoViewIfNeeded()
  await expect(summary).toBeVisible()
  const box = (await summary.boundingBox())!
  expect(Math.abs(box.y + box.height / 2 - 422)).toBeLessThan(2)
})

test('calendar dates are valid and original placeholders migrate without losing edits', () => {
  expect(parseCeremonyDate('2026-02-30')).toBeNull()
  expect(parseCeremonyDate('2028-02-29')).not.toBeNull()
  expect(ceremonyLabel('2026-11-07', '19:20')).toBe('2026년 11월 7일 토요일\n오후 7시 20분')
  const legacy = structuredClone(defaults)
  legacy.copy.groom = '신랑 이름'; legacy.copy.bride = '신부 이름'
  legacy.copy.venueName = '더링크호텔'
  legacy.copy.greetingMessage = '직접 편집한 인사말'
  legacy.intro.rotation = 27
  const migrated = parseConfig(legacy)
  expect(migrated.copy.groom).toBe('정주현')
  expect(migrated.copy.bride).toBe('임하니')
  expect(migrated.copy.venueName).toBe(defaults.copy.venueName)
  expect(migrated.copy.greetingMessage).toBe('직접 편집한 인사말')
  expect(migrated.intro.rotation).toBe(27)
  expect(() => parseConfig({ ...defaults, copy: { ...defaults.copy, ceremonyDate: '2026-02-30' } })).toThrow()
})

test('calendar and account editing persist, and copying includes bank and account', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.setViewportSize({width:390, height:844})
  await page.goto('draft/')
  await expect(page.locator('.draft-couple')).toContainText('정주현')
  await expect(page.locator('.draft-couple')).toContainText('임하니')
  await expect(page.locator('.draft-calendar tbody td').filter({hasText:/^\d/})).toHaveCount(30)
  await expect(page.locator('.is-wedding-day')).toHaveText('7♥')
  await page.locator('#edit-date summary').click()
  await page.getByLabel('예식 일시 · 예식 날짜').fill('2028-02-29')
  await page.getByLabel('예식 일시 · 예식 시간').fill('12:00')
  await page.reload()
  await expect(page.locator('.is-wedding-day')).toHaveText('29♥')
  await expect(page.locator('.draft-calendar caption')).toContainText('FEBRUARY')
  await expect(page.locator('.draft-date-text')).toContainText('오후 12시')
  await page.getByRole('button', {name:'신랑측 계좌 안내', exact:true}).click()
  await expect(page.locator('.draft-account-group.groom li')).toHaveCount(3)
  await page.getByRole('button', {name:'정주현 은행명과 계좌번호 복사', exact:true}).click()
  await expect(page.locator('.draft-account-status')).toContainText('복사했어요')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(`${defaults.copy.groomAccountBank} ${defaults.copy.groomAccountNumber}`)
  await page.locator('#edit-accounts summary').click()
  await page.getByLabel('마음 전하실 곳 · 신랑측 2 · 계좌번호').fill('')
  await page.reload()
  await page.getByRole('button', {name:'신랑측 계좌 안내', exact:true}).click()
  await expect(page.locator('.draft-account-group.groom li')).toHaveCount(2)
  await page.getByRole('button', {name:'미리보기 ▶'}).click()
  await expect(page.locator('#edit-accounts')).toHaveCount(0)
})

test('body copy saves immediately, migrates legacy data and has a separate preview URL', async ({ page, context }) => {
  await page.goto('draft/')
  const legacy = JSON.parse(JSON.stringify(defaults))
  delete legacy.copy
  legacy.intro.rotation = 17
  await page.evaluate(value => localStorage.setItem('wedding-draft-v1', JSON.stringify(value)), legacy)
  await page.reload()
  await expect(page.locator('.draft-location h2')).toHaveText('오시는 길')
  await page.locator('#edit-greeting summary').click()
  await page.getByLabel('인사말 · 인사말', {exact:true}).fill('우리의 첫 걸음\n함께해 주세요.')
  await page.reload()
  await expect(page.locator('.draft-greeting>p').first()).toHaveText('우리의 첫 걸음\n함께해 주세요.')
  await page.locator('#edit-greeting summary').click()
  await page.getByLabel('인사말 · 초대 문구', {exact:true}).fill('')
  const previewPage = await context.newPage()
  await previewPage.goto('draft/?mode=preview')
  await expect(previewPage.locator('.draft-copy-editor')).toHaveCount(0)
  await expect(previewPage.locator('.draft-inspector')).toHaveCount(0)
  await expect(previewPage.locator('.draft-intro-layer .draft-letter-position')).toHaveAttribute('style', /rotate\(17deg\)/)
  await page.getByLabel('인사말 · 신랑 이름', {exact:true}).fill('신랑 테스트')
  await expect(previewPage.locator('.draft-couple')).toContainText('신랑 테스트')
  await previewPage.reload()
  await expect(previewPage.locator('.draft-studio')).toHaveClass(/is-preview/)
  await expect(previewPage.locator('.draft-greeting>p').nth(1)).toHaveText('')
  await previewPage.getByRole('button', {name:'편집으로'}).click()
  await expect(previewPage).not.toHaveURL(/mode=preview/)
  await expect(previewPage.locator('#edit-greeting')).toBeAttached()
  await previewPage.close()
})

test('draft contains ceremony details and a deferred venue map', async ({ page }) => {
  await page.setViewportSize({ width:390, height:844 })
  await page.goto('draft/')
  await expect(page.locator('.draft-date-text')).toContainText('2026년 11월 7일 토요일')
  await expect(page.locator('.draft-date-card')).toContainText('오후 7시 20분')
  await expect(page.locator('.draft-ceremony-hour')).toHaveText('오후 7시 20분')
  await expect(page.locator('.draft-ceremony-venue')).toHaveText('더링크서울 트리뷰트 포트폴리오 호텔 3층 베일리홀')
  await expect(page.locator('.draft-ceremony-hour')).toHaveCSS('font-size', await page.locator('.draft-date-text').evaluate(el => getComputedStyle(el).fontSize))
  await expect(page.locator('.draft-ceremony-venue')).toHaveCSS('font-weight','650')
  await expect(page.locator('.draft-location-card')).toContainText('3층 베일리홀')
  await expect(page.locator('.draft-location-card address')).toHaveText('서울특별시 구로구 경인로 610')
  await expect(page.getByText('지도가 보이지 않으면 위 버튼으로 열어주세요.', {exact:true})).toHaveCount(0)
  await expect(page.getByAltText('더링크호텔 주변 네이버지도')).toHaveAttribute('loading', 'lazy')
  await page.locator('.draft-location').scrollIntoViewIfNeeded()
  await expect(page.getByRole('region', {name:'더링크호텔 네이버지도 미리보기'})).toBeVisible()
  await expect(page.getByAltText('더링크호텔 주변 네이버지도')).toHaveAttribute('src', /images\/draft\/venue-naver-map\.png/)
  await expect(page.getByRole('link', {name:'더링크호텔 네이버지도 크게 보기', exact:true})).toHaveAttribute('href', /map\.naver\.com/)
  await expect(page.locator('.draft-map-links img')).toHaveCount(2)
  await expect(page.getByRole('link', {name:'네이버지도 ↗'})).toHaveAttribute('href', /map\.naver\.com/)
  await expect(page.getByRole('link', {name:'카카오맵 ↗'})).toHaveAttribute('href', /map\.kakao\.com/)
})

test('compact account rows, animated accessible disclosure and readable full venue name', async ({ page }) => {
  await page.setViewportSize({width:320, height:700})
  await page.goto('draft/')
  const trigger = page.getByRole('button', {name:'신랑측 계좌 안내', exact:true})
  const panel = page.locator('.groom .draft-account-panel')
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(panel).toHaveAttribute('inert', '')
  await trigger.click()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(trigger).toHaveCSS('font-weight', '700')
  await expect(panel).not.toHaveAttribute('inert', '')
  const row = page.getByRole('button', {name:'정주현 은행명과 계좌번호 복사', exact:true})
  await expect(row).toBeVisible()
  expect(await row.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  for (const account of await page.locator('.groom .draft-account-copy').all()) expect(await account.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  const name = (await row.locator('strong').boundingBox())!
  const number = (await row.locator('.draft-account-number').boundingBox())!
  await expect(row.locator('.draft-account-number')).toHaveCSS('font-size','15px')
  await expect(row.locator('.draft-account-number')).toHaveCSS('font-weight','700')
  for (const selector of ['strong', '.draft-account-bank']) {
    await expect(row.locator(selector)).toHaveCSS('font-size','15px')
    await expect(row.locator(selector)).toHaveCSS('font-weight','700')
  }
  await expect(trigger).toHaveCSS('font-size','14px')
  await expect(row.locator('.draft-account-copy-icon')).toBeVisible()
  const iconPositions = await page.locator('.groom .draft-account-copy-icon').evaluateAll(els => els.map(el => el.getBoundingClientRect().x))
  expect(Math.max(...iconPositions) - Math.min(...iconPositions)).toBeLessThan(1)
  expect(Math.abs(name.y + name.height/2 - number.y - number.height/2)).toBeLessThan(2)
  await trigger.press('Enter')
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(panel).toHaveAttribute('inert', '')
  await expect(panel).toHaveCSS('opacity', '0')
  const venue = page.locator('.draft-location-title')
  expect(await venue.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await expect(page.locator('.draft-couple')).toHaveCSS('font-size', '24px')
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(panel).toHaveCSS('transition-duration', '0s')
})

test('pink hall, floating caption and icon-only glass BGM switch', async ({ page }) => {
  await page.setViewportSize({width:320,height:700})
  await page.goto('draft/?mode=preview')
  const toggle = page.getByRole('switch', {name:'배경음악',exact:true})
  await expect(toggle).toHaveAttribute('aria-checked','false')
  await expect(toggle).toHaveText('')
  expect(await toggle.locator('.draft-bgm-glass').evaluate(el => {
    const style = getComputedStyle(el)
    return [style.backdropFilter, style.getPropertyValue('-webkit-backdrop-filter')].some(value => value.includes('blur(10px)'))
  })).toBe(true)
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-checked','true')
  await toggle.press('Space')
  await expect(toggle).toHaveAttribute('aria-checked','false')
  await expect(page.locator('audio')).toHaveCount(0)
  await expect(page.locator('.draft-invitation .draft-bgm')).toHaveCount(1)
  await expect(page.locator('.draft-bgm-dock')).toHaveCSS('position','sticky')
  await expect(page.locator('.draft-bgm-glass')).toHaveCSS('height','28px')
  await expect(toggle.locator('svg')).toHaveAttribute('width','12')
  await expect(toggle.locator('.draft-bgm-track>span')).toHaveCSS('width','12px')
  await expect(toggle).toHaveCSS('color','rgb(255, 249, 234)')
  const bgm = (await toggle.boundingBox())!, controls = (await page.locator('.draft-preview-controls').boundingBox())!
  expect(controls.x + controls.width).toBeLessThanOrEqual(bgm.x)
  await expect(page.locator('.draft-ceremony-hall')).toHaveCSS('color','rgb(185, 68, 112)')
  await expect(page.locator('.draft-scroll-note')).toHaveCSS('animation-name','draft-scroll-float')
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.locator('.draft-scroll-note')).toHaveCSS('animation-name','none')
})

test('BGM stays inside the invitation on desktop and while scrolling', async ({ page }) => {
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('draft/')
  const inside = async () => {
    const card = (await page.locator('.draft-invitation').boundingBox())!
    const bgm = (await page.locator('.draft-bgm-glass').boundingBox())!
    expect(bgm.x).toBeGreaterThan(card.x)
    expect(bgm.x + bgm.width).toBeLessThan(card.x + card.width)
  }
  await inside()
  await page.locator('.draft-date').scrollIntoViewIfNeeded()
  await inside()
  expect((await page.locator('.draft-bgm-glass').boundingBox())!.y).toBeLessThan(60)
  await page.getByRole('button', {name:'미리보기 ▶'}).click()
  await inside()
})

test('English section labels are larger and titles smaller in both modes', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('draft/')
  const verify = async () => {
    for (const label of await page.locator('.draft-section-index>span').all()) await expect(label).toHaveCSS('font-size','12px')
    for (const heading of await page.locator('.draft-poster-section h2').all()) {
      const size = await heading.evaluate(el => parseFloat(getComputedStyle(el).fontSize))
      expect(size).toBeGreaterThanOrEqual(27)
      expect(size).toBeLessThanOrEqual(36)
      const accent = heading.locator('em')
      if (await accent.count()) expect(await accent.evaluate(el => parseFloat(getComputedStyle(el).fontSize))).toBe(size)
    }
  }
  await verify()
  await page.getByRole('button', {name:'미리보기 ▶'}).click()
  await verify()
})

test('memory-board photos have unequal sizes, settle on scroll and respect reduced motion', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('draft/?mode=preview')
  await page.getByRole('button', {name:'건너뛰기'}).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  const board = page.getByRole('group', {name:'사진을 붙인 메모리 보드'})
  await expect(board.locator('.draft-photo-pin')).toHaveCount(8)
  await expect(board.locator('.draft-empty-frame')).toHaveCount(6)
  await expect(board.locator('.draft-photo-caption')).toHaveCount(0)
  expect(await page.locator('.draft-gallery').evaluate(el => el.getBoundingClientRect().height)).toBeLessThanOrEqual(844)
  await expect(board.locator('button')).toHaveCount(2)
  await board.scrollIntoViewIfNeeded()
  for (const pin of await board.locator('.draft-photo-pin').all()) {
    await pin.scrollIntoViewIfNeeded()
    await expect(pin).toHaveClass(/is-pinned/)
    await expect(pin.locator('.draft-photo-print')).toHaveCSS('animation-name','draft-photo-land')
    await expect(pin.locator('.draft-photo-print')).toHaveCSS('opacity','1')
  }
  const sizes = await board.locator('.draft-photo-pin').evaluateAll(els => els.map(el => el.clientWidth))
  expect(sizes[0]).toBeGreaterThan(sizes[1])
  await expect(board).toHaveCSS('background-image','none')
  await expect(board).toHaveCSS('background-color','rgba(0, 0, 0, 0)')
  await board.getByRole('button', {name:'메인 커버 사진 보기'}).click()
  await expect(page.locator('.draft-lightbox')).toBeVisible()
  const viewer = page.locator('.draft-lightbox')
  await expect(viewer).toHaveCSS('touch-action','none')
  await expect(viewer.locator('img')).toHaveAttribute('draggable','false')
  await expect(viewer.locator('img')).toHaveCSS('user-select','none')
  await expect(viewer.locator('[download]')).toHaveCount(0)
  for (const label of ['이전 사진','다음 사진']) {
    const arrow = viewer.getByRole('button', {name:label})
    await expect(arrow).toHaveText('')
    const centers = await arrow.evaluate(el => ({button:el.getBoundingClientRect().top + el.getBoundingClientRect().height / 2, photo:el.parentElement!.getBoundingClientRect().top + el.parentElement!.getBoundingClientRect().height / 2}))
    expect(Math.abs(centers.button - centers.photo)).toBeLessThan(1)
  }
  await viewer.getByRole('button', {name:'다음 사진'}).click()
  await expect(viewer.locator('img')).toHaveAttribute('alt','인트로 사진 보기')
  await viewer.getByRole('button', {name:'이전 사진'}).click()
  await expect(viewer.locator('img')).toHaveAttribute('alt','메인 커버 사진 보기')
  await page.getByRole('button', {name:'사진 보기 닫기'}).click()
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(board.locator('.will-pin')).toHaveCount(0)
  for (const button of await board.locator('button').all()) {
    await expect(button).toHaveCSS('animation-name','none')
    await expect(button).toHaveCSS('opacity','1')
  }
})

test('each section plays its own motion only when its content enters view', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('draft/?mode=preview')
  await page.getByRole('button', {name:'건너뛰기'}).click()
  const card = page.locator('.draft-date-card')
  await expect(card).not.toHaveClass(/is-in-view/)
  for (const [selector, animation] of [
    ['.draft-greeting h2','draft-title-land'],
    ['.draft-flower','draft-flower-turn'],
    ['.draft-date-card','draft-card-drop'],
    ['.draft-location-card','draft-card-drop'],
    ['.draft-accounts','draft-card-drop'],
    ['.draft-poster-footer strong','draft-body-rise'],
  ]) {
    const item = page.locator(selector)
    await item.scrollIntoViewIfNeeded()
    await expect(item).toHaveClass(/is-in-view/)
    await expect(item).toHaveCSS('animation-name',animation)
    await expect(item).toHaveCSS('opacity','1')
  }
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.locator('.draft-motion-item')).toHaveCount(0)
  await expect(card).toHaveCSS('opacity','1')
})

test('editor and preview share the flower color and tilted calendar', async ({ page }) => {
  await page.goto('draft/')
  const flower = page.locator('.draft-flower'), calendar = page.locator('.draft-date-card')
  await expect(flower).toHaveCSS('opacity', '1')
  const color = await flower.evaluate(el => getComputedStyle(el).color)
  const rotation = await calendar.evaluate(el => getComputedStyle(el).transform)
  expect(rotation).not.toBe('none')
  await page.getByRole('button', {name:'미리보기 ▶'}).click()
  await page.getByRole('button', {name:'건너뛰기'}).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  await page.locator('.draft-greeting').scrollIntoViewIfNeeded()
  await expect(flower).toHaveCSS('opacity', '1')
  await expect(flower).toHaveCSS('color', color)
  await page.locator('.draft-date').scrollIntoViewIfNeeded()
  await expect(calendar).toHaveCSS('transform', rotation)
  await expect(calendar).toHaveCSS('opacity', '1')
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.reload()
  await expect(flower).toHaveCSS('opacity', '1')
  await expect(calendar).toHaveCSS('transform', rotation)
})

test('map heart stays centered on the source hotel icon at every screen size', async ({ page }) => {
  await page.goto('draft/')
  for (const width of [320, 390, 1440]) {
    await page.setViewportSize({width, height:844})
    await page.locator('.draft-location-map').scrollIntoViewIfNeeded()
    const map = (await page.locator('.draft-naver-map>img').boundingBox())!
    const heart = (await page.locator('.draft-naver-heart').boundingBox())!
    expect(Math.abs(heart.x + heart.width / 2 - (map.x + map.width * 883 / 1377))).toBeLessThan(1)
    expect(Math.abs(heart.y + heart.height / 2 - (map.y + map.height * 425 / 850))).toBeLessThan(1)
  }
})

test('legacy yellow migration, rotation handle, persistence and playback', async ({ page }) => {
  await page.setViewportSize({ width:1440, height:1000 })
  await page.goto('draft/')
  const legacy = JSON.parse(JSON.stringify(defaults))
  delete legacy.intro.rotation; delete legacy.main.rotation
  legacy.intro.color = '#FFF5DE'; legacy.intro.text = 'Our\nWedding'; legacy.intro.y = 26
  await page.evaluate(value => localStorage.setItem('wedding-draft-v1', JSON.stringify(value)), legacy)
  await page.reload()
  await expect(page.getByLabel('레터링 색상')).toHaveValue('#f4d84f')
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('Our\nWedding')
  await expect(page.getByLabel('세로 위치', {exact:true})).toHaveValue('26')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  const selection = page.locator('.draft-selection')
  const rotator = page.getByRole('slider', {name:'문구 회전 핸들'})
  await rotator.scrollIntoViewIfNeeded()
  const handle = (await rotator.boundingBox())!, block = (await selection.boundingBox())!
  const cx = block.x + block.width/2, cy = block.y + block.height/2
  const radius = cy - (handle.y + handle.height/2)
  await page.mouse.move(handle.x + handle.width/2, handle.y + handle.height/2)
  await page.mouse.down(); await page.mouse.move(cx + radius*.5, cy - radius*Math.sqrt(3)/2, {steps:8}); await page.mouse.up()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('30')
  await page.getByRole('button', {name:'되돌리기', exact:true}).click()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  await page.getByLabel('회전 각도', {exact:true}).fill('-18')
  await expect(selection).toHaveAttribute('style', /rotate\(-18deg\)/)
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('wedding-draft-v1')!).intro.rotation)).toBe(-18)
  await page.reload()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('-18')
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name:'설정 내보내기'}).click()
  const exported = await download
  await page.getByRole('button', {name:'수평으로', exact:true}).click()
  await page.locator('input[type=file]').setInputFiles((await exported.path())!)
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('-18')
  await page.getByRole('button', {name:'메인 커버', exact:true}).click()
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('0')
  await page.getByLabel('회전 각도', {exact:true}).fill('12')
  await page.getByRole('button', {name:'미리보기 ▶'}).click()
  await expect(page.locator('.draft-intro-layer .draft-letter-position')).toHaveAttribute('style', /rotate\(-18deg\)/)
  await page.getByRole('button', {name:'건너뛰기'}).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  await expect(page.locator('.draft-cover-layer .draft-letter-position')).toHaveAttribute('style', /rotate\(12deg\)/)
})

test('edit, drag, resize, save, export/import and independent scene settings', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  const config = () => page.evaluate(() => JSON.parse(localStorage.getItem('wedding-draft-v1')!))
  const selection = page.getByRole('group', { name: '문구 이동 및 크기 조절' })
  const initialBox = (await selection.boundingBox())!
  await page.mouse.move(initialBox.x + 40, initialBox.y + 40)
  await page.mouse.down(); await page.mouse.move(initialBox.x + 40, initialBox.y + 90, { steps: 8 }); await page.mouse.up()
  await expect.poll(async () => (await config()).intro.y).toBeGreaterThan(25)
  await page.getByRole('button', { name: '되돌리기', exact: true }).click()
  await expect.poll(async () => (await config()).intro.y).toBe(22)
  await selection.dblclick()
  await page.getByLabel('사진 위에서 문구 편집').fill('Together\nforever')
  await page.getByLabel('사진 위에서 문구 편집').press('Escape')
  await expect(selection.locator('svg')).toHaveAttribute('aria-label', 'Together\nforever')
  await selection.focus(); await page.keyboard.press('ArrowDown')
  await expect.poll(async () => (await config()).intro.y).toBe(23)
  const handle = page.getByRole('slider', { name: '문구 크기 핸들' })
  await handle.focus(); await handle.press('ArrowLeft')
  await expect.poll(async () => (await config()).intro.width).toBe(85)
  const corner = (await handle.boundingBox())!
  await page.mouse.move(corner.x + 8, corner.y + 8); await page.mouse.down()
  await page.mouse.move(corner.x - 12, corner.y + 8, { steps: 5 }); await page.mouse.up()
  await expect.poll(async () => (await config()).intro.width).toBeLessThan(85)
  await page.getByRole('button', { name: '메인 커버', exact: true }).click()
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Wedding\nInvitation')
  await page.getByLabel('사진 위 문구', { exact: true }).fill('Our\nWedding')
  await page.getByRole('button', { name: '미스트 블루 배경' }).click()
  await expect(page.locator('.draft-poster-body')).toHaveCSS('background-color', 'rgb(234, 240, 245)')
  await expect.poll(async () => (await config()).main.text).toBe('Our\nWedding')
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Together\nforever')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '설정 내보내기' }).click()
  const exportFile = await download
  expect(exportFile.suggestedFilename()).toBe('wedding-draft.json')
  await page.getByRole('button', { name: '이 장면 초기화' }).click()
  await page.locator('input[type=file]').setInputFiles((await exportFile.path())!)
  await expect(page.getByLabel('사진 위 문구', { exact: true })).toHaveValue('Together\nforever')
  await page.getByLabel('사진 위 문구', { exact: true }).fill('한글')
  await expect(page.locator('.draft-notice')).toContainText('기본 글꼴')
  await expect(selection.locator('svg')).toHaveAttribute('aria-label', '한글')
  await page.locator('input[type=file]').setInputFiles({ name:'invalid.json', mimeType:'application/json', buffer:Buffer.from('{"version":100}') })
  await expect(page.locator('.draft-notice')).toContainText('파일 형식')
})

test('empty text and immediate reload retain position and rotation', async ({ page }) => {
  await page.setViewportSize({width:1440,height:1000})
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', {name:'문구 편집', exact:false}).click()
  const input = page.getByLabel('사진 위에서 문구 편집')
  await input.press('ControlOrMeta+A')
  await input.press('Backspace')
  await page.getByRole('button', {name:'편집 완료'}).click()
  await page.getByLabel('세로 위치', {exact:true}).fill('35')
  await page.getByLabel('회전 각도', {exact:true}).fill('12')
  // Intentionally no polling or delay before reload: edits must already be durable.
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('')
  await expect(page.getByLabel('세로 위치', {exact:true})).toHaveValue('35')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('12')
  await page.getByRole('button', {name:'문구 편집', exact:false}).click()
  await page.getByLabel('사진 위에서 문구 편집').pressSequentially('Our wedding')
  await page.getByRole('button', {name:'편집 완료'}).click()
  await page.getByRole('button', {name:'지금 저장', exact:true}).click()
  await expect(page.locator('.draft-notice')).toContainText('새로고침해도 유지')
  await page.reload()
  await expect(page.getByLabel('사진 위 문구', {exact:true})).toHaveValue('Our wedding')
  await expect(page.getByLabel('회전 각도', {exact:true})).toHaveValue('12')
})

test('intro transitions, replay, gallery and mobile editing', async ({ page }) => {
  await page.setViewportSize({ width:390, height:844 })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', { name:'문구 · 배경 편집' }).click()
  await expect(page.getByLabel('사진 위 문구', { exact:true })).toBeVisible()
  await page.getByRole('button', { name:'메인 커버', exact:true }).click()
  await page.getByRole('button', { name:'편집 도구 닫기' }).click()
  await expect(page.locator('.draft-letter-svg')).toHaveAttribute('aria-label', 'Wedding\nInvitation')
  await page.screenshot({ path:'/private/tmp/wedding-draft-mobile-edit.png' })
  await page.getByRole('button', { name:'미리보기 ▶' }).click()
  await expect(page.locator('.draft-intro-layer')).toBeVisible()
  await expect(page.locator('.draft-cover-layer svg')).toHaveCount(0)
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0, {timeout:10000})
  await expect(page.locator('.draft-cover-layer svg')).toBeVisible()
  await expect(page.locator('.draft-cover-layer .draft-write').last()).toHaveCSS('clip-path', 'none', { timeout:5000 })
  await page.screenshot({ path:'/private/tmp/wedding-draft-mobile-cover.png' })
  await page.locator('.draft-greeting').scrollIntoViewIfNeeded()
  await expect(page.locator('.draft-greeting h2')).toHaveCSS('opacity', '1')
  await page.screenshot({ path:'/private/tmp/wedding-draft-body.png' })
  await page.getByRole('button', { name:'다시 재생' }).click()
  await expect(page.locator('.draft-intro-layer')).toBeVisible()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0, {timeout:10000})
  await page.getByRole('button', { name:'메인 커버 사진 보기' }).click()
  await expect(page.locator('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('dialog')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('short screens, viewport bounds and reduced motion', async ({ page }) => {
  await page.setViewportSize({width:320,height:568})
  await page.emulateMedia({ reducedMotion:'reduce' })
  await page.goto('draft/')
  await expect(page.locator('.draft-letter-svg')).toBeVisible()
  await page.getByRole('button', { name:'문구 · 배경 편집' }).click()
  await page.getByLabel('가로 위치', {exact:true}).fill('0')
  await page.getByLabel('세로 위치', {exact:true}).fill('0')
  await page.getByRole('button', { name:'편집 도구 닫기' }).click()
  const block = (await page.locator('.draft-selection').boundingBox())!
  const stage = (await page.locator('.draft-stage').boundingBox())!
  expect(block.x).toBeGreaterThanOrEqual(stage.x - 1)
  expect(block.y).toBeGreaterThanOrEqual(stage.y - 1)
  await page.getByRole('button', { name:'미리보기 ▶' }).click()
  await expect(page.locator('.draft-write').first()).toHaveCSS('animation-name','none')
  await page.getByRole('button', { name:'건너뛰기' }).click()
  await expect(page.locator('.draft-intro-layer')).toHaveCount(0)
  await page.getByRole('button', { name:'편집으로' }).click()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})
