import { useState } from 'react'

// Generated by Kakao Map's official “HTML 태그 복사” for the hotel coordinates.
// Keep the original map/logo intact; no API key or third-party credentials needed.
const imageUrl = 'https://staticmap.kakao.com/map/mapservice?FORMAT=PNG&SCALE=2.5&MX=474325&MY=1112745&S=0&IW=504&IH=310&LANG=0&COORDSTM=WCONGNAMUL&logo=kakao_logo'
const mapUrl = 'https://map.kakao.com/link/map/더링크호텔,37.5052943,126.8838555'

export default function DraftMap() {
  const [failed, setFailed] = useState(false)
  return <div className="draft-location-map" role="region" aria-label="더링크호텔 카카오지도 미리보기">
    <a className="draft-kakao-map" href={mapUrl} target="_blank" rel="noopener noreferrer" aria-label="더링크호텔 카카오지도 크게 보기">
      <img src={imageUrl} width="504" height="310" loading="lazy" decoding="async" alt="더링크호텔 주변 카카오지도" onError={() => setFailed(true)} />
      {!failed && <span className="draft-kakao-marker"><strong>더링크호텔</strong><span>♥</span></span>}
    </a>
    {failed && <p className="draft-map-error" role="status">지도를 불러오지 못했어요. 아래 지도 버튼을 이용해주세요.</p>}
    <a className="draft-kakao-credit" href={mapUrl} target="_blank" rel="noopener noreferrer"><img src="https://t1.kakaocdn.net/localimg/localimages/07/2018/pc/common/logo_kakaomap.png" width="72" height="16" alt="카카오맵" /><span>지도 크게 보기 ↗</span></a>
  </div>
}
