export const copyDefaults = {
  introCaption: 'TOGETHER, A NEW BEGINNING', coverCaption: 'OUR NEXT CHAPTER',
  coverGroomName: 'Juhyeon', coverBrideName: 'Hani',
  tickerLeft: 'WITH YOU, ALWAYS', tickerRight: 'A NEW CHAPTER',
  greetingLabel: 'THE INVITATION', greetingTitle: '우리', greetingAccent: '결혼합니다.',
  greetingMessage: '아내를 사랑하는 남편\n남편을 위로하는 아내가 되어\n하나님이 기뻐하시는\n아름다운 가정을 이루겠습니다.',
  greetingInvite: '따뜻한 마음으로 오셔서\n저희의 새로운 시작을\n축복해 주시면 감사하겠습니다.', groom: '정주현', bride: '임하니',
  groomParents: '정우선 · 김인숙의 장남', brideParents: '임춘구 · 박건자의 장녀',
  dateLabel: 'SAVE THE DATE', dateTitle: '정중히', dateAccent: '초대합니다.',
  dateYear: '2026 · OUR DAY', dateStamp: '11. 07. SAT', dateText: '2026년 11월 7일 토요일\n오후 7시 20분',
  ceremonyDate: '2026-11-07', ceremonyTime: '19:20', ceremonyEndTime: '21:00',
  galleryLabel: 'MOMENTS OF US', galleryTitle: '우리의', galleryAccent: '빛나는 순간들',
  galleryMessage: '함께 웃던 순간을 모아.', galleryFirst: 'IN THE GARDEN', gallerySecond: 'SIDE BY SIDE',
  galleryNote: '갤러리 구성은 사진을 추가하며 다듬을 예정입니다.',
  locationLabel: 'MEET US HERE', locationTitle: '오시는 길',
  venueName: '더링크서울 트리뷰트 포트폴리오 호텔', venueHall: '3층 베일리홀', venueAddress: '서울특별시 구로구 경인로 610',
  transitStop: '신도림역 1번 출구에서 800m', transport: '',
  rsvpLabel: 'WITH LOVE', rsvpTitle: '당신과 함께라서', rsvpAccent: '더 특별한 하루.',
  rsvpMessage: '참석 여부 안내는\n정보가 정해지면 연결할 예정입니다.',
  accountsLabel: 'WITH GRATITUDE', accountsTitle: '마음 전하실 곳',
  accountsMessage: '축하해 주시는 따뜻한 마음,\n소중히 간직하겠습니다.',
  groomAccountName: '정주현', groomAccountBank: '우리은행', groomAccountNumber: '1002-333-956265',
  groomFamily1Name: '정우선', groomFamily1Bank: '국민은행', groomFamily1Number: '703-21-0347-405',
  groomFamily2Name: '김인숙', groomFamily2Bank: '국민은행', groomFamily2Number: '444401-01-290683',
  brideAccountName: '임하니', brideAccountBank: '신한은행', brideAccountNumber: '110-401-127905',
  footerLabel: 'BLUE MEETS PINK.', footerTitle: 'Better, together.', footerNote: 'OUR WEDDING INVITATION',
}
export type DraftCopy = typeof copyDefaults
export type CopyKey = keyof DraftCopy
export const copyGroups: Record<string, { title: string; fields: [CopyKey, string][] }> = {
  cover: { title:'커버', fields:[['introCaption','인트로 하단 문구'],['coverCaption','메인 하단 문구'],['coverGroomName','메인 신랑 영문 이름'],['coverBrideName','메인 신부 영문 이름']] },
  greeting: { title:'인사말', fields:[['tickerLeft','띠 문구 왼쪽'],['tickerRight','띠 문구 오른쪽'],['greetingLabel','영문 소제목'],['greetingTitle','제목'],['greetingAccent','강조 제목'],['greetingMessage','인사말'],['greetingInvite','초대 문구'],['groomParents','신랑 부모님 및 관계'],['groom','신랑 이름'],['brideParents','신부 부모님 및 관계'],['bride','신부 이름']] },
  date: { title:'예식 일시', fields:[['dateLabel','영문 소제목'],['dateTitle','제목'],['dateAccent','강조 제목'],['ceremonyDate','예식 날짜'],['ceremonyTime','예식 시간'],['ceremonyEndTime','캘린더 종료 시간']] },
  gallery: { title:'갤러리', fields:[['galleryLabel','영문 소제목'],['galleryTitle','제목'],['galleryAccent','강조 제목'],['galleryMessage','소개 문구']] },
  location: { title:'오시는 길', fields:[['locationLabel','영문 소제목'],['locationTitle','제목'],['venueName','예식장 이름'],['venueHall','층과 홀'],['venueAddress','주소'],['transitStop','지하철 출구 안내'],['transport','교통 및 주차 안내']] },
  rsvp: { title:'참석 안내', fields:[['rsvpLabel','영문 소제목'],['rsvpTitle','제목'],['rsvpAccent','강조 제목'],['rsvpMessage','안내 문구']] },
  accounts: { title:'마음 전하실 곳', fields:[['accountsLabel','영문 소제목'],['accountsTitle','제목'],['accountsMessage','안내 문구'],['groomAccountName','신랑측 1 · 예금주'],['groomAccountBank','신랑측 1 · 은행'],['groomAccountNumber','신랑측 1 · 계좌번호'],['groomFamily1Name','신랑측 2 · 예금주'],['groomFamily1Bank','신랑측 2 · 은행'],['groomFamily1Number','신랑측 2 · 계좌번호'],['groomFamily2Name','신랑측 3 · 예금주'],['groomFamily2Bank','신랑측 3 · 은행'],['groomFamily2Number','신랑측 3 · 계좌번호'],['brideAccountName','신부측 · 예금주'],['brideAccountBank','신부측 · 은행'],['brideAccountNumber','신부측 · 계좌번호']] },
  footer: { title:'마무리', fields:[['footerLabel','윗 문구'],['footerTitle','중앙 문구'],['footerNote','아랫 문구']] },
}
